name: Release and Main Workflow

on:
  pull_request:
    branches: ["main", "release*"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd coffee-project
          npm i

      - name: Run eslint check
        run: |
          cd coffee-project
          npm run lint

      - name: Run the frontend tests
        run: |
          cd coffee-project
          npm run test -- --coverageThreshold='{"global":{"statements":"80","branches":"80","functions":"80","lines":"80"}}'
          npm run test -- -o --coverageThreshold='{"global":{"statements":"80","branches":"80","functions":"80","lines":"80"}}'
